---
- name: Install and Configure Firezone for WireGuard VPN
  hosts: all
  become: yes

  tasks:
    - name: Install prerequisites for Docker
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        update_cache: yes

    - name: Add Docker’s official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Install Docker Engine
      apt:
        name: docker-ce
        update_cache: yes
        state: latest

    - name: Download Firezone Install Script
      get_url:
        url: https://raw.githubusercontent.com/firezone/firezone/legacy/scripts/install.sh
        dest: /tmp/install_firezone.sh
        mode: '0755'

    - name: Run Firezone installation script with expect for interactive prompts
      expect:
        command: "sh -c /tmp/install_firezone.sh"
        responses:
          "(?i).*administrator email.*:": "admin@example.com"
          "(?i).*installation directory.*:": "\n"
          "(?i).*external URL.*:": "https://firezone1.librekit.com"
          "(?i).*product feedback.*\\(Y/n\\):": "Y"
          "(?i).*crash and performance logs.*\\(N/y\\):": "N"
          "(?i).*Press <ENTER> to install.*:": "\n"
      timeout: 600  # Adjust the timeout as needed
      register: script_output
      changed_when: false
      ignore_errors: yes
      
    - name: Debug script output
      debug:
        var: script_output.stdout_lines
        
    - name: Configure Firezone
      block:
        - name: Set external URL and SSL certificate path in Firezone configuration
          lineinfile:
            path: /etc/firezone/firezone.rb
            regexp: '{{ item.regexp }}'
            line: '{{ item.line }}'
          loop:
            - { regexp: "^# default\\['firezone'\\]\\['external_url'\\] = ''", line: "default['firezone']['external_url'] = 'https://firezone1.librekit.com'" }
            - { regexp: "^default\\['firezone'\\]\\['ssl'\\]\\['certificate'\\] = nil", line: "default['firezone']['ssl']['certificate'] = '/etc/letsencrypt/live/firezone1.librekit.com/fullchain.pem'" }
            - { regexp: "^default\\['firezone'\\]\\['ssl'\\]\\['certificate_key'\\] = nil", line: "default['firezone']['ssl']['certificate_key'] = '/etc/letsencrypt/live/firezone1.librekit.com/privkey.pem'" }

    - name: Reconfigure Firezone
      command: firezone-ctl reconfigure

    - name: Create or reset Firezone admin user
      command: firezone-ctl create-or-reset-admin
